version: '3.8'
services:
  pg_sql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=engquizz
    ports:
      - '5432:5432'